name: CI Security Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read      
  security-events: write  
  actions: read

jobs:
  # 1. Build & Unit Test
  build-and-test:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm install
          
      - name: Run Unit Tests
        run: npx jest --forceExit --detectOpenHandles

  # 2. Security Scan (SAST)
  security-scan:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: 'javascript-typescript'
          
      - name: Perform Analysis
        uses: github/codeql-action/analyze@v3

  # 3. Build Image & Scan
  container-security:
    needs: security-scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Docker Image
        run: docker build -t my-app:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0 
        with:
          image-ref: 'my-app:${{ github.sha }}'
          format: 'table'
          exit-code: '0' 
          severity: 'CRITICAL,HIGH'